/**
 * Standardized API response types for consistent error handling
 */

export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: ApiError;
  meta?: ApiMeta;
}

export interface ApiError {
  code: string;
  message: string;
  details?: any;
  timestamp: string;
  requestId?: string;
}

export interface ApiMeta {
  page?: number;
  limit?: number;
  total?: number;
  hasNext?: boolean;
  hasPrev?: boolean;
}

export interface PaginatedResponse<T> {
  items: T[];
  meta: Required<ApiMeta>;
}

/**
 * Standard API error codes
 */
export const API_ERROR_CODES = {
  // Authentication & Authorization
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  
  // Resource Management
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  
  // Business Logic
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  INVALID_STATE: 'INVALID_STATE',
  
  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
  // File/Document specific
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  
  // Form specific
  FORM_NOT_FOUND: 'FORM_NOT_FOUND',
  FORM_VALIDATION_FAILED: 'FORM_VALIDATION_FAILED',
  FORM_ALREADY_SUBMITTED: 'FORM_ALREADY_SUBMITTED',
  FORM_GENERATION_FAILED: 'FORM_GENERATION_FAILED',
  
  // OCR specific
  OCR_PROCESSING_FAILED: 'OCR_PROCESSING_FAILED',
  OCR_DISABLED: 'OCR_DISABLED',
  UNSUPPORTED_DOCUMENT_TYPE: 'UNSUPPORTED_DOCUMENT_TYPE',
  
  // Employee specific
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_ALREADY_EXISTS: 'EMPLOYEE_ALREADY_EXISTS',
  EMPLOYEE_ALREADY_TERMINATED: 'EMPLOYEE_ALREADY_TERMINATED',
  
  // Organization specific
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_ACCESS_DENIED: 'ORGANIZATION_ACCESS_DENIED',
} as const;

export type ApiErrorCode = keyof typeof API_ERROR_CODES;

/**
 * HTTP status codes mapping to API error codes
 */
export const HTTP_STATUS_MAP: Record<ApiErrorCode, number> = {
  // 400 Bad Request
  VALIDATION_ERROR: 400,
  INVALID_INPUT: 400,
  MISSING_REQUIRED_FIELD: 400,
  BUSINESS_RULE_VIOLATION: 400,
  FORM_VALIDATION_FAILED: 400,
  FORM_ALREADY_SUBMITTED: 400,
  INVALID_FILE_TYPE: 400,
  OCR_DISABLED: 400,
  UNSUPPORTED_DOCUMENT_TYPE: 400,
  EMPLOYEE_ALREADY_TERMINATED: 400,
  
  // 401 Unauthorized
  AUTHENTICATION_REQUIRED: 401,
  INVALID_TOKEN: 401,
  TOKEN_EXPIRED: 401,
  
  // 403 Forbidden
  INSUFFICIENT_PERMISSIONS: 403,
  ORGANIZATION_ACCESS_DENIED: 403,
  
  // 404 Not Found
  RESOURCE_NOT_FOUND: 404,
  FORM_NOT_FOUND: 404,
  FILE_NOT_FOUND: 404,
  EMPLOYEE_NOT_FOUND: 404,
  ORGANIZATION_NOT_FOUND: 404,
  
  // 409 Conflict
  RESOURCE_ALREADY_EXISTS: 409,
  RESOURCE_CONFLICT: 409,
  EMPLOYEE_ALREADY_EXISTS: 409,
  
  // 413 Payload Too Large
  FILE_TOO_LARGE: 413,
  
  // 422 Unprocessable Entity
  OPERATION_NOT_ALLOWED: 422,
  INVALID_STATE: 422,
  
  // 429 Too Many Requests
  RATE_LIMIT_EXCEEDED: 429,
  TOO_MANY_REQUESTS: 429,
  
  // 500 Internal Server Error
  INTERNAL_SERVER_ERROR: 500,
  DATABASE_ERROR: 500,
  FORM_GENERATION_FAILED: 500,
  OCR_PROCESSING_FAILED: 500,
  FILE_UPLOAD_FAILED: 500,
  
  // 502 Bad Gateway
  EXTERNAL_SERVICE_ERROR: 502,
  
  // 503 Service Unavailable
  SERVICE_UNAVAILABLE: 503,
};